version: '3.3'
services:
  nginx:
    image: nginx
    container_name: vesaapp_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/defualt.conf
    ports:
      - "80:80"
    links:
      - app
    restart: always
    environment:
      - NGINX_HOST=zionmaori.com
      - NGINX_UPSTREAM_NAME=versa_app
  app:
    image:  zionmaori/node-vesra:latest
    container_name: versa_app
    environment: 
      - VIRTUAL_HOST=zionmaori.com
      - NODE_ENV=production
    ports:
      - "3000"
    restart: always
    

    
