version: '3.3'
services:
  nginx:
    image: nginx
    container_name: vesaapp_nginx
    volumes:
<<<<<<< HEAD
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/logs/nginx/
=======
      - ./nginx/default.conf:/etc/nginx/conf.d/defualt.conf
>>>>>>> ea97f56b99fd4de80aec1a92b9e14eb462922802
    ports:
      - "80:80"
    links:
      - app
    restart: always
    environment:
      - NGINX_HOST=zionmaori.com
      - NGINX_UPSTREAM_NAME=versa_app
  app:
    image:  zionmaori/node-vesra:latest
    container_name: versa_app
    environment: 
      - VIRTUAL_HOST=zionmaori.com
      - NODE_ENV=production
    ports:
      - "3000"
    restart: always
    

    
